title = "Devops Week News"
baseurl = "http://devopsweeknews.com/"
languageCode = "en-us"
copyright = "DevOps Week News 2018"
theme = "ghostwriter"

[Params]
    intro = true
    headline = "Devops Week News"
    description = "Weekly newsletter with curated articles about DevOps."
    github = "https://github.com/orgs/devopsweeknews"
    twitter = "https://twitter.com/devopsweeknews"
    shareTwitter = true
    opengraph = true

[[menu.main]]
    name = "Issues"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Subscribe"
    url = "/subscribe/"
    weight = 2
